@startuml
left to right direction
actor "Utilizator" as user
rectangle "Aplicație / Administrează Liste de CF-uri" {
  usecase "Vizualizează Listele cu CF-uri\n[[lista_cf_vizualizare.svg]]" as UC1
  usecase "Caută CF in Listele de CF-uri\n[[lista_cf_cautare.svg]]" as UC1
  usecase "Adaugă Listă de CF-uri\n[[lista_cf_adauga.svg]]" as UC2
  usecase "Modifică Listă de CF-uri\n[[lista_cf_modifica.svg]]" as UC3
  usecase "Șterge Listă de CF-uri\n[[lista_cf_sterge.svg]]" as UC4
  usecase "Importă Listă de CF-uri\n[[lista_cf_importa.svg]]" as UC4
  usecase "Exportă Listă de CF-uri\n[[lista_cf_exporta.svg]]" as UC4
}
user --> UC1
user --> UC2
user --> UC3
user --> UC4
@enduml
