@startuml
title Creează Sesiune de verificare
start
:Selectază zonele de interes;
->
:Descarcă imaginile satelitare pentru zonele de interes de la privider-ul ales;
->
:Filtrare opțională a parcelelor pe baza selecției de Liste de CF-uri (includere/excludere);
->
:Descarcă parcele din zonele de interes conținând posibile clădri de pe serverul ANCPI;
stop
@enduml
