@startuml
left to right direction
actor "Utilizator" as user
rectangle Aplicatie {
  usecase "Administrează Zone de interes din UAT\n[[zona_interes_admin.svg]]" as UC1
  usecase "Adminstrează Liste de CF-uri\n[[lista_cf_admin.svg]]" as UC2
  usecase "Adminstrează Sesiunile de verificare\n[[sesiune_verificare_admin.svg]]" as UC3
}
user --> UC1
user --> UC2
user --> UC3
@enduml
